action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: False

runner: "SSD_parallel"

buffer_size: 64
batch_size_run: 64
batch_size: 64

# env_args:
#   state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200

td_lambda: 0.8

agent: "SSD" # Default rnn agent
agent_output_type: "pi_logits"

critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "QPC"
lr: 0.0001 # Learning rate for agents
critic_lr: 0.0001 # Learning rate for critics
Q_tot_w: 0.01

t_max: 100000000 # Stop running after this many timesteps


out_channels: 8
kernel_size: [3,3]

cooperation: 0.001

chaowangluo: True   # whether to use the chaowangluo 批评家

learner: "QPC_ALL_Learner" 

use_single_rewards: True   #环境奖励是使用局部奖励还是全局奖励

# QPC_single_reward: False    #QPC是否使用局部奖励拟合环境奖励

use_coo_grad: True  #是否使用合作梯度 

use_TLoss: True  #是否使用全局批评家损失 
